### PR TITLE
Future intake value not allow.

### PR DESCRIPTION
**Pull request by kulisarawiangin**
set maxdate is today.

### CODE REVIEW

**Comment by kulisarawiangin** [comment]
Is it ok to merge ka?

**Comment by Siripa-Maneein** [comment]
Please, remove unused comment in this one also ka.
Screen Shot 2565-11-26 at 23 24 03

**Comment by kulisarawiangin** [comment]
> Please, remove unused comment in this one also ka. Screen Shot 2565-11-26 at 23 24 03

already delete it ka.

**Comment by kulisarawiangin** [comment]
Is it ok to merge kab.

**Comment by Siripa-Maneein** [comment]
Approve ka.

**Pull request merged**
