### PR TITLE
500 server error for cron job fixed.

### PR DESCRIPTION
**Pull request by Siripa-Maneein**
- Ensure that token is not None for send_notification method.
- Update update_notification method in views.py so that the time will be updated correctly even if the notification is turned off.

### CODE REVIEW

**Comment by Siripa-Maneein** [comment]
Is it ok to merge?

**Comment by jindasy** [comment]
approve

**Comment by PloyyNK** [comment]
Approve

**Comment by kulisarawiangin** [comment]
approve

**Pull request merged**
