### PR TITLE
Add max value notification hour

### PR DESCRIPTION
**Pull request by kulisarawiangin**

### CODE REVIEW

**Comment by Siripa-Maneein** [comment]
Should delete the unused comment ka.
Screen Shot 2565-11-26 at 22 39 27

**Comment by kulisarawiangin** [comment]
Is it ready to merge ka?

**Comment by kulisarawiangin** [comment]
> Should delete the unused comment ka. Screen Shot 2565-11-26 at 22 39 27

delete it already ka.

**Comment by Siripa-Maneein** [comment]
Approve.

**Pull request merged**
