### PR TITLE
Iteration1

### PR DESCRIPTION
**Pull request by Siripa-Maneein**
Initialize a django project and update README.md. Is it Ok to merge?

### CODE REVIEW

**Comment by Siripa-Maneein** [comment]
Hide sensitive data with python-decouple.

**Comment by jindasy** [comment]
Wrong heading format in README.md; please add space after ## of Description and Project Documents.

**Comment by Siripa-Maneein** [comment]
Thanks. Already fixed. Anything else?

**Comment by jindasy** [comment]
Approve

**Comment by kulisarawiangin** [comment]
Approve

**Comment by PloyyNK** [comment]
Approve

**Pull request merged**
