### PR TITLE
improve next button in regis.html

### PR DESCRIPTION
**Pull request by kulisarawiangin**

### CODE REVIEW

**Comment by kulisarawiangin** [comment]
Is it ok to merge ka?

**Comment by Siripa-Maneein** [comment]
The button position is quite strange when I run.
Screen Shot 2565-11-26 at 16 56 15

**Comment by kulisarawiangin** [comment]
> The button position is quite strange when I run. Screen Shot 2565-11-26 at 16 56 15

please try again  ka i'm already fix it.

**Comment by Siripa-Maneein** [comment]
approve.

**Pull request merged**
